### PR TITLE
Fix selecting user methods in generic methods

### PR DESCRIPTION
**Pull request by trejjam**
# Fix selecting user methods in generic methods

## Description

The following mapping:
```cs
partial TTarget Map<TTarget>(object source);

partial B MapToBInternal(A source);

B MapToB(A source) => MapToBInternal(source);
```

Generates the `Map` method using `MapToBInternal`.

## Note
This should be an issue, but I already wrote failing tests...
I am happy to finish it. I would like a hint where the solution should take place. I guess it should be in `UserMethodMappingExtractor.ExtractUserMappings`. I would use some kind of weighted list to select the correct method, but maybe there is another simpler solution.

## Checklist

- [x] The existing code style is followed
- [x] The commit message follows our guidelines
- [x] Performed a self-review of my code
- [x] Hard-to-understand areas of my code are commented
- [x] The documentation is updated (as applicable)
- [x] Unit tests are added/updated
- [x] Integration tests are added/updated (as applicable, especially if feature/bug depends on roslyn or framework version in use)

### CODE REVIEW

**Comment by trejjam** [comment]
ObjectFactory moved to #1234

**Review by latonz — APPROVED** [review]
Thank you for this contribution!

**Comment by latonz** [comment]
I just noticed the .net framework integration test is not yet updated, could you update that one? Thank you!

**Comment by trejjam** [comment]
It should be ready now

**Review by latonz — APPROVED** [review]

**Pull request merged**
