### PR TITLE
feat: add support for "." wildcard

### PR DESCRIPTION
**Pull request by zeidoo**
# Adding support for "." wildcard

## Description
If you don’t want explicitly name all properties from nested source bean, you can use . as target. This will tell Mapperly to map every property from source bean to target object.

Inspired by:
https://mapstruct.org/documentation/stable/reference/html/#mapping-nested-bean-properties-to-current-target

Currently a WIP. Please let me know what to add for this to be merge eventually.

## Checklist

- [x] The existing code style is followed
- [x] The commit message follows our guidelines
- [x] Performed a self-review of my code
- [ ] Hard-to-understand areas of my code are commented
- [ ] The documentation is updated (as applicable)
- [x] Unit tests are added/updated
- [ ] Integration tests are added/updated (as applicable, especially if feature/bug depends on roslyn or framework version in use)

### CODE REVIEW

**Comment by zeidoo** [comment]
Please also note I added a test that verifies that a user defined [MapProperty] takes precedence over the PropertyNameMappingStrategy.

**Comment by latonz** [comment]
@zeidoo thank you for opening this PR. Doesn't this address the same use-case as we planned to address with https://github.com/riok/mapperly/issues/453?

**Comment by zeidoo** [comment]
I guess it does. Didn't see that issue.

I would say that mapperly is closer to mapstruct than it is to automapper in its usage. I would favor mapstruct's "." syntax instead of a dedicated attribute. 

Ultimately, both work. Let me know which you prefer and I can change the PR if needed.

Ps: if we follow mapstruct's way, we get free documentation ;)

**Comment by latonz** [comment]
In my opinion, `MapNestedProperties` describes better what happens. It is clearer to a reader of the code what is being configured. I don't think documentation will be a problem, as Mapperly uses its own documentation anyway, which should always be kept up to date and also be the place to go for users. Further, I think more users of Mapperly are familiar with Automapper than with MapStruct. Therefore I prefer the proposed `MapNestedProperties` API design.

**Comment by wrestlerdude** [comment]
+1 

Desperately need this. In my view mapping the properties for like flattening and unflattening with attributes not only defeats the purpose of a mapper in the first place - it is less ergonomic than mapping them manually.

**Pull request closed without merging**
