### PR TITLE
feat: optimize BuildMemberPathCandidates

### PR DESCRIPTION
**Pull request by TimothyMakkison**
## Description
Optimized `BuildMemberPathCandidates` by using a faster string concat and early yield.

- Changed `BuildMemberPathCandidates` to immediately `yield return` the full string, this way the same string isn't cloned. This is significant because most matches are identical.
- `BuildName` uses an array of lengths of the split members to get the corresponding substring of the permutation. In this case `Substring` is faster than `string.Concat` because .NET already knows the final length of the string so a simple copy is performed. `string.Concat` doesn't know the size of the final string and has to iterate through the strings, adding each one to the `ValueStringBuilder`.
- Added more `BuildMemberPathCandidatesShouldWork` and adapted `StringChunkerTest`.
- Deleted `Chunk` and all corresponding tests.

See #479, this change doesn't alter algorithm, so the nasty big O behaviour is still present, but it will reduce memory and yield a small speed boost.

## Benchmarks
Saved 300KB of memory for larger compilations. Note that for large unmatching members with capital letters, we see a speed up of 33% and almost half the memory usage.

**Old**
|       Method |      Mean |     Error |    StdDev |      Gen0 |     Gen1 |  Allocated |
|------------- |----------:|----------:|----------:|----------:|---------:|-----------:|
|      Compile |  1.614 ms | 0.0232 ms | 0.0206 ms |   74.2188 |  15.6250 |  167.84 KB |
| LargeCompile | 59.971 ms | 0.9963 ms | 1.1473 ms | 1428.5714 | 285.7143 | 9283.43 KB |

|       Method |      Mean |     Error |    StdDev |      Gen0 |     Gen1 |  Allocated |
|------------- |----------:|----------:|----------:|----------:|---------:|-----------:|
|      Compile |  1.605 ms | 0.0301 ms | 0.0267 ms |   78.1250 |  19.5313 |  170.23 KB |
| LargeCompile | 59.858 ms | 1.1878 ms | 2.1114 ms | 1428.5714 | 285.7143 | 9268.93 KB |

|       Method |      Mean |     Error |    StdDev |      Gen0 |     Gen1 |  Allocated |
|------------- |----------:|----------:|----------:|----------:|---------:|-----------:|
|      Compile |  1.621 ms | 0.0213 ms | 0.0188 ms |   82.0313 |  19.5313 |  167.99 KB |
| LargeCompile | 60.269 ms | 0.7791 ms | 0.8660 ms | 1428.5714 | 428.5714 | 9268.14 KB |

**New**
|       Method |      Mean |     Error |    StdDev |    Median |      Gen0 |     Gen1 |  Allocated |
|------------- |----------:|----------:|----------:|----------:|----------:|---------:|-----------:|
|      Compile |  1.685 ms | 0.0502 ms | 0.1424 ms |  1.625 ms |   82.0313 |  19.5313 |  165.29 KB |
| LargeCompile | 60.405 ms | 1.8495 ms | 5.1249 ms | 57.832 ms | 1428.5714 | 428.5714 | 8960.02 KB |

|       Method |      Mean |     Error |    StdDev |      Gen0 |     Gen1 |  Allocated |
|------------- |----------:|----------:|----------:|----------:|---------:|-----------:|
|      Compile |  1.530 ms | 0.0234 ms | 0.0207 ms |   78.1250 |  15.6250 |  166.27 KB |
| LargeCompile | 56.023 ms | 0.5765 ms | 0.5393 ms | 1375.0000 | 250.0000 | 8961.08 KB |

|       Method |      Mean |     Error |    StdDev |      Gen0 |     Gen1 |  Allocated |
|------------- |----------:|----------:|----------:|----------:|---------:|-----------:|
|      Compile |  1.567 ms | 0.0240 ms | 0.0388 ms |   78.1250 |  15.6250 |  166.45 KB |
| LargeCompile | 58.106 ms | 1.0849 ms | 1.9563 ms | 1375.0000 | 375.0000 | 8967.22 KB |

**Old with long unmatching full caps member**
|  Method |     Mean |    Error |   StdDev |      Gen0 |    Gen1 | Allocated |
|-------- |---------:|---------:|---------:|----------:|--------:|----------:|
| Compile | 23.73 ms | 0.250 ms | 0.209 ms | 6406.2500 | 62.5000 |    9.6 MB |

**New with long unmatching full caps member**
|  Method |     Mean |    Error |   StdDev |      Gen0 |    Gen1 | Allocated |
|-------- |---------:|---------:|---------:|----------:|--------:|----------:|
| Compile | 17.57 ms | 0.314 ms | 0.590 ms | 3656.2500 | 62.5000 |   5.52 MB |

### Substring vs string.Concat
Skip 2 Take 2
|    Method |      Mean |    Error |   StdDev |    Median |   Gen0 | Allocated |
|---------- |----------:|---------:|---------:|----------:|-------:|----------:|
| SubString |  30.87 ns | 2.656 ns | 7.833 ns |  28.45 ns | 0.0306 |      48 B |
|    Concat | 166.60 ns | 2.966 ns | 3.750 ns | 167.23 ns | 0.0918 |     144 B |

Take first
|    Method |     Mean |    Error |   StdDev |   Gen0 | Allocated |
|---------- |---------:|---------:|---------:|-------:|----------:|
| SubString | 18.81 ns | 0.459 ns | 0.659 ns | 0.0204 |      32 B |
|    Concat | 73.55 ns | 1.366 ns | 1.278 ns | 0.0305 |      48 B |

### CODE REVIEW

**Review by latonz — CHANGES_REQUESTED** [review]
Thank you for another performance optimisation 👍 
I found it quite hard to understand the length based approach and therefore tried around a little... Wouldn't the readability improve while keeping the performance benefits by using an index based approach? Build a list of all upper case char indices in the string, loop through all permutations and build the string based on the indices. I did not benchmark it yet, but I think this could be an easier to understand solution with an acceptable performance. WDYT?

```c#
    internal static IEnumerable<IEnumerable<string>> BuildMemberPathCandidates(string name)
    {
        if (name.Length == 0)
            yield break;

        // yield full string
        yield return new []{ name };

        var indices = GetPascalCaseSplitIndices(name).ToArray();

        // try all permutations, skipping the first because the full string is already yielded
        var permutationsCount = 1 << indices.Length;
        for (var i = 1; i < permutationsCount; i++)
        {
            yield return BuildName(name, indices, i);
        }
    }

    private static IEnumerable<string> BuildName(string source, IEnumerable<int> splitIndices, int enabledSplitPositions)
    {
        var lastSplitIndex = 0;
        var currentSplitPosition = 1;
        foreach (var splitIndex in splitIndices)
        {
            if ((enabledSplitPositions & currentSplitPosition) == currentSplitPosition)
            {
                yield return source.Substring(lastSplitIndex, splitIndex - lastSplitIndex);
                lastSplitIndex = splitIndex;
            }

            currentSplitPosition <<= 1;
        }

        if (lastSplitIndex < source.Length)
            yield return source.Substring(lastSplitIndex);
    }

    private static IEnumerable<int> GetPascalCaseSplitIndices(string str)
    {
        var i = 1;
        foreach (var c in str.Skip(1))
        {
            if (!char.IsUpper(c))
            {
                i++;
                continue;
            }

            yield return i;
            i++;
        }
    }
```

**Comment by TimothyMakkison** [comment]
> Build a list of all upper case char indices in the string, loop through all permutations and build the string based on the indices. I did not benchmark it yet, but I think this could be an easier to understand solution with an acceptable performance. WDYT?

This is very similar to what I originally wanted. It's why my variable names are a little wrong (offsets not indices) 😂 
I ended up using the offsets because I kept getting a nasty OBOE and looping infintely. I'll use your offset system.

**Comment by TimothyMakkison** [comment]
- Deleted `StringChunker` and associated tests.
- Changed `GetPascalCaseSplitIndices` to use a for loop instead of foreach. 
- Modifed `splitIndices` in `BuildName` to accept an array instead of `IEnumerable`.

### Benchmarks
Doesn't appear to be a regression.

#### New
|       Method |      Mean |     Error |     StdDev |      Gen0 |     Gen1 |  Allocated |
|------------- |----------:|----------:|-----------:|----------:|---------:|-----------:|
|      Compile |  2.317 ms | 0.1589 ms |  0.4686 ms |   78.1250 |  15.6250 |  166.27 KB |
| LargeCompile | 78.160 ms | 3.8618 ms | 11.3260 ms | 1400.0000 | 200.0000 | 8964.42 KB |

|       Method |      Mean |     Error |     StdDev |      Gen0 |     Gen1 |  Allocated |
|------------- |----------:|----------:|-----------:|----------:|---------:|-----------:|
|      Compile |  1.997 ms | 0.0979 ms |  0.2856 ms |   78.1250 |  15.6250 |  167.88 KB |
| LargeCompile | 78.429 ms | 5.0801 ms | 14.6573 ms | 1250.0000 | 250.0000 | 8947.21 KB |

#### Unmodifed
|       Method |      Mean |     Error |     StdDev |      Gen0 |     Gen1 |  Allocated |
|------------- |----------:|----------:|-----------:|----------:|---------:|-----------:|
|      Compile |  2.063 ms | 0.0981 ms |  0.2829 ms |   78.1250 |  15.6250 |  169.48 KB |
| LargeCompile | 78.972 ms | 3.5745 ms | 10.3704 ms | 1400.0000 | 400.0000 | 9266.61 KB |

|       Method |      Mean |     Error |     StdDev |      Gen0 |     Gen1 |  Allocated |
|------------- |----------:|----------:|-----------:|----------:|---------:|-----------:|
|      Compile |  2.778 ms | 0.2019 ms |  0.5952 ms |   93.7500 |  23.4375 |  169.26 KB |
| LargeCompile | 80.579 ms | 4.3258 ms | 11.7687 ms | 1500.0000 | 500.0000 | 9247.04 KB |


#### New with long member
|       Method |      Mean |     Error |    StdDev |       Gen0 |      Gen1 | Allocated |
|------------- |----------:|----------:|----------:|-----------:|----------:|----------:|
|      Compile |  25.62 ms |  1.649 ms |  4.837 ms |  3642.8571 |   71.4286 |   5.55 MB |

**Comment by latonz** [comment]
@TimothyMakkison after rebase, I'll merge it 😊

**Comment by latonz** [comment]
Mapperly doesn't reference `System.Memory`. The .net framework integration tests should reference net48 🤔  Therefore I'm wondering why Span does work in the integration tests too...

**Pull request merged**
